# Общая конфигурация проекта
site_name: "Лабораторная работа: Кастомный сайт и CI/CD"
site_description: "Проект с кастомной темой для MkDocs и сборкой через GitHub Actions."
site_author: "Семён Кондауров"

# Указываем MkDocs использовать нашу кастомную тему
theme:
  name: null
  custom_dir: 'theme/'

# Структура навигации
nav:
  - Главная: index.md
  - Установка: setup.md
